# -*- coding: utf-8 -*-
"""Praktek Luas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KoqNuDbFRCeYvs3er8kw8Z0yOBtHkGST
"""

print("Program Menghitung Luas Ruangan dan Konversi Inci ke Meter")

# Input panjang dalam inci
panjang_inci = float(input("Masukkan panjang ruangan (dalam inci): "))
# Input lebar dalam inci
lebar_inci = float(input("Masukkan lebar ruangan (dalam inci): "))

# Konversi inci ke meter
panjang_meter = panjang_inci * 0.0254  # 1 inci = 0.0254 meter
lebar_meter = lebar_inci * 0.0254      # 1 inci = 0.0254 meter

# Hitung luas dalam meter persegi
luas_meter = panjang_meter * lebar_meter

# Tampilkan hasil konversi dan luas
print(f"Panjang dalam meter: {panjang_meter:.2f} m")
print(f"Lebar dalam meter: {lebar_meter:.2f} m")
print(f"Luas ruangan adalah {luas_meter:.2f} meter persegi.")






print("Program Menghitung Luas Ruangan dan Konversi Meter ke Inci")

# Input panjang dan lebar dalam meter
panjang_meter = float(input("Masukkan panjang ruangan (dalam meter): "))
lebar_meter = float(input("Masukkan lebar ruangan (dalam meter): "))

# Konversi meter ke inci
panjang_inci = panjang_meter * 39.3701  # 1 meter = 39.3701 inci
lebar_inci = lebar_meter * 39.3701      # 1 meter = 39.3701 inci

# Hitung luas dalam meter persegi
luas_meter = panjang_meter * lebar_meter


# Tampilkan hasil konversi dan luas
print(f"Panjang dalam inci: {panjang_inci:.2f} inci")
print(f"Lebar dalam inci: {lebar_inci:.2f} inci")
print(f"Luas ruangan adalah {luas_meter:.2f} meter persegi.")